version: "3"
services:
  signal-server:
    build: 
      context: .
    restart: always
    expose:
      - 3000
    networks:
      - proxy_network

  webserver:
    image: nginx:latest
    depends_on:
      - signal-server
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/acme.sh:/etc/acme.sh:ro
    networks:
      - proxy_network

networks:
  proxy_network:
